version: "3.0"

services:
  trigger:
    build: .
    links:
      - redis
      - celery
    volumes:
      - .:/data/repo
      - /share/logs:/data/logs
    command:
      python manage.py trigger game_index "http://store.steampowered.com/search/?category1=998&sort_by=Released_DESC"

  celery:
    build: .
    links:
      - redis
    volumes:
      - .:/data/repo
      - /share/logs:/data/logs
    environment:
     - crawl_worker_http_proxy=172.17.0.1:8123
     - crawl_worker_https_proxy=172.17.0.1:8123
    command:
      celery -A manage:steam worker -l info

  redis:
    image: redis
