version: "3.0"

services:
  trigger:
    build: .
    links:
      - redis
      - celery
    volumes:
      - .:/data/repo
    command:
      python manage.py trigger game_list "http://store.steampowered.com/search/?page=1"

  celery:
    build: .
    deploy:
      replicas: 2
    links:
      - redis
    volumes:
      - .:/data/repo
    environment:
     - crawl_worker_http_proxy=172.17.0.1:8123
     - crawl_worker_https_proxy=172.17.0.1:8123
    command:
      celery -A manage:steam worker -l info

  redis:
    image: redis
