version: "3.0"

services:
  trigger:
    build: .
    links:
      - redis
      - celery
    volumes:
      - .:/data/repo
    command:
      python manage.py trigger game_list "http://store.steampowered.com/search/?page=1"

  celery:
    build: .
    links:
      - redis
    volumes:
      - .:/data/repo
    command:
      celery -A manage:steam worker -l info

  redis:
    image: redis
